# Generated by Django 6.0.3 on 2026-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0002_remove_databasestats_code_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='db_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='db_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='db_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='db_port',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='db_user',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
