# Generated by Django 6.0.3 on 2026-03-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0003_platformsettings_db_host_platformsettings_db_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='db_password',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='db_user',
        ),
    ]
