# Generated by Django 6.0.3 on 2026-03-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='enrollment_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='enrollment_status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('pending', 'Pending Approval'), ('rejected', 'Rejected')], default='enrolled', max_length=10),
        ),
    ]
