# Generated by Django 6.0.3 on 2026-03-31 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('resource_approved', 'Resource Approved'), ('resource_rejected', 'Resource Rejected'), ('grade_added', 'Grade Added'), ('grade_modified', 'Grade Modified'), ('assignment_graded', 'Assignment Graded'), ('settings_changed', 'Settings Changed'), ('bulk_import', 'Bulk Import'), ('certificate_issued', 'Certificate Issued'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
