# Generated by Django 6.0.3 on 2026-03-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('user_updated', 'User Updated'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('resource_uploaded', 'Resource Uploaded'), ('resource_approved', 'Resource Approved'), ('resource_rejected', 'Resource Rejected'), ('resource_deleted', 'Resource Deleted'), ('resource_downloaded', 'Resource Downloaded'), ('room_created', 'Room Created'), ('room_deleted', 'Room Deleted'), ('room_joined', 'Room Joined'), ('room_left', 'Room Left'), ('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('quiz_created', 'Quiz Created'), ('quiz_deleted', 'Quiz Deleted'), ('quiz_submitted', 'Quiz Submitted'), ('quiz_toggled', 'Quiz Active Toggled'), ('assignment_created', 'Assignment Created'), ('assignment_deleted', 'Assignment Deleted'), ('assignment_submitted', 'Assignment Submitted'), ('assignment_graded', 'Assignment Graded'), ('grade_added', 'Grade Added'), ('grade_modified', 'Grade Modified'), ('grade_deleted', 'Grade Deleted'), ('attendance_marked', 'Attendance Marked'), ('forum_topic_created', 'Forum Topic Created'), ('forum_topic_deleted', 'Forum Topic Deleted'), ('forum_post_created', 'Forum Post Created'), ('event_created', 'Event Created'), ('event_deleted', 'Event Deleted'), ('event_attended', 'Event Attended'), ('announcement_created', 'Announcement Created'), ('announcement_deleted', 'Announcement Deleted'), ('message_sent', 'Message Sent'), ('certificate_issued', 'Certificate Issued'), ('certificate_deleted', 'Certificate Deleted'), ('badge_awarded', 'Badge Awarded'), ('settings_changed', 'Settings Changed'), ('bulk_import', 'Bulk Import'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('password_reset', 'Password Reset'), ('data_exported', 'Data Exported')], max_length=30),
        ),
    ]
