# Generated by Django 6.0.3 on 2026-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('librarian', 'Librarian'), ('counselor', 'Counselor'), ('coordinator', 'Coordinator'), ('staff', 'Staff'), ('admin', 'Admin'), ('administration', 'Administration')], default='student', max_length=20),
        ),
    ]
